# Generated by Django 4.1.6 on 2023-09-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelModelNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=20)),
                ('Employee Id', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
